methodNameMap:
  abuseFilterCheckMatch:
  abuseFilterCheckSyntax:
  abuseFilterEvalExpression:
  abuseFilterUnblockAutoPromote:
  abuseLogPrivateDetails: ViewAbuseLogPrivateDetails
  block:
  checkToken:
  clearHasMsg:
  clientLogin:
  collection+addArticle: AddArticleToCollection
  collection+addCategory: AddCategoryToCollection
  collection+addChapter: AddChapterToCollection
  collection+clearCollection: ClearCollection
  collection+postCollection: PostPagesToCollection
  collection+removeArticle: RemovePageFromCollection
  collection+removeItem: RemoveItemFromCollection
  collection+renameChapter: RenameCollectionChapter
  collection+setSorting: SetCollectionSorting
  collection+setTitles: SetCollectionTitle
  collection+sortItems: SortCollectionItems
  collection+suggestArticleAction: SuggestCollectionArticleAction
  collection+suggestUndoArticleAction: SuggestUndoCollectionArticleAction
  compare:
  createAccount:
  createLocalAccount:
  delete: DeletePage
  deleteGlobalAccount:
  edit:
  emailUser:
  flow+edit-header: EditHeader
  flow+edit-post: EditPost
  flow+edit-title: EditTitle
  flow+edit-topic-summary: EditTopicSummary
  flow+lock-topic: LockTopic
  flow+moderate-post: ModeratePost
  flow+moderate-topic: ModerateTopic
  flow+new-topic: NewTopic
  flow+view-header: ViewHeader
  flow+view-post-history: ViewPostHistory
  flow+view-post: ViewPost
  flow+view-topic-history: ViewTopicHistory
  flow+view-topic: ViewTopic
  globalBlock:
  import:
  login:
  logout:
  manageTags:
  massMessage:
  mergeHistory:
  move:
  newsletterSubscribe: subscribeNewsletter
  none:
  parse:
  protect:
  purge:
  removeAuthenticationData:
  resetPassword:
  revisionDelete: deleteRevision
  rollback:
  searchTranslations:
  shortenURL:
  thank:
  transcodeReset: resetTranscode
  unblock:
  undelete:
  unlinkAccount:
  upload:
  validatePassword:
  watch:
  wikilove: sendWikilove
routes:
  - AbuseFilterCheckMatch
  - AbuseFilterCheckSyntax
  - AbuseFilterEvalExpression
  - AbuseFilters
  - AbuseFilterUnblockAutoPromote
  - AbuseLog
  - AllCategories
  - AllDeletedRevisions
  - AllFileUsages
  - AllImages
  - AllLinks
  - AllMessages
  - AllPages
  - AllRedirects
  - AllRevisions
  - AllTransclusions
  - AllUsers
  - AuthManagerInfo
  - Babel
  - BackLinks
  - BetaFeatures
  - Blocks
  - Categories
  - CategoryInfo
  - CategoryMembers
  - CentralNoticeActiveCampaigns
  - CentralNoticeLogs
  - CheckUser
  - CheckUserLog
  - CirrusBuildDoc
  - CirrusCompSuggestBuildDoc
  - CirrusDoc
  - contributors
  - DeletedRevisions
  - DeletedRevs
  - Description
  - DuplicateFiles
  - EmbeddedIn
  - ExtDistBranches
  - ExtDistRepos
  - ExtLinks
  - Extracts
  - ExtURLUsage
  - FeatureUsage
  - FileArchive
  - FileRepoinfo
  - FileUsage
  - FlowInfo
  - GadgetCategories
  - Gadgets
  - GlobalAllUsers
  - GlobalBlocks
  - GlobalGroups
  - GlobalPreferences
  - GlobalRenameStatus
  - GlobalUsage
  - GlobalUserInfo
  - ImageInfo
  - Images
  - ImageUsage
  - Info
  - IWBackLinks
  - IWLinks
  - LangBackLinks
  - LangLinks
  - LanguageInfo
  - LanguageStats
  - Links
  - LinksHere
  - LintErrors
  - LinterStats
  - LogEvents
  - Main
  - ManageMessageGroups
  - MapData
  - MessageCollection
  - MessageGroups
  - MessageGroupStats
  - MessageTranslations
  - MmContent
  - MostViewed
  - MyStashedFiles
  - notifications
  - oath
  - PageImages
  - PagePropNames
  - PageProps
  - PageSwithProp
  - PageTerms
  - PageViews
  - ParamInfo
  - PrefixSearch
  - ProtectedTitles
  - QueryPage
  - random
  - ReadingListEntries
  - ReadingLists
  - RecentChanges
  - Redirects
  - Revisions
  - Search
  - SiteInfo
  - SiteViews
  - StashImageInfo
  - Tags
  - Templates
  - Threads
  - Tokens
  - TranscludedIn
  - TranscodeStatus
  - TranslationReview
  - UnlinkAccount
  - UnreadNotificationPages
  - UserContribs
  - UserInfo
  - UserRights
  - Users
  - VideoInfo
  - Watchlist
  - WatchlistRaw
  - WbEntityUsage
  - WbListEntityUsage
  - Wikibase
  - Wikisets
params:
  - activeUsers
  - alertContinue
  - alertUnreadFirst
  - allowedOnly
  - allRev
  - archiveName
  - assertUser
  - assignKnownUsers
  - attachedWiki
  - badFileContextTitle
  - captchaId
  - captchaWord
  - centralAuthToken
  - checkStatus
  - contentFormat
  - contentModel
  - convertTitles
  - crossWikiSummary
  - curTimestamp
  - deletedOnly
  - deleteTalk
  - diffTo
  - diffToText
  - diffToTextPst
  - disableEditSection
  - disableLimitReport
  - disableStyleDeduplication
  - disableTOC
  - effectiveLangLinks
  - enabledOnly
  - enableParser
  - endHexSortKey
  - endSortKey
  - endSortKeyPrefix
  - errorFormat
  - errorLang
  - errorsUseLocal
  - excludeGroup
  - excludeRights
  - excludeUser
  - excludeUser
  - expandTemplates
  - expandUrl
  - extMetadataFilter
  - extMetadataLanguage
  - extMetadataMultiLang
  - feedFormat
  - fileIds
  - fileKey
  - fileSize
  - filterLangLinks
  - filterLocal
  - filterRedir
  - formatVersion
  - fromContentFormat
  - fromContentModel
  - fromId
  - fromPst
  - fromRev
  - fromSection
  - fromSlots
  - fromText
  - fromTitle
  - fullHistory
  - generateTitles
  - generateXML
  - hideAnons
  - hideBots
  - hideCategorization
  - hideLiu
  - hideMinor
  - hideMyself
  - hidePatrolled
  - iconSize
  - ignoreWarnings
  - includeLocal
  - inLanguageCode
  - interwikiPrefix
  - interwikiSource
  - invertTags
  - langCode
  - langProp
  - lastAction
  - limiterProfile
  - linkContext
  - localOnly
  - logId
  - maxAge
  - maxLag
  - maxSize
  - maxTokenAge
  - mergeRequestFields
  - messageContinue
  - messageFormat
  - messageUnreadFirst
  - metadataVersion
  - minSize
  - mobileFormat
  - moveSubpages
  - moveTalk
  - newOnly
  - newParent
  - noContent
  - noRedirect
  - notifierTypes
  - numberInGroup
  - oldId
  - oldImage
  - onlyPst
  - pageId
  - pageIds
  - preserveState
  - prExpiry
  - prFilterCascade
  - prLevel
  - PrType
  - rcId
  - realName
  - recursiveSubmodules
  - renderLevel
  - renderMaxDepth
  - renderMaxThreadCount
  - renderStartRepliesAt
  - renderThreadCount
  - renderThreadPos
  - requestId
  - requestsFor
  - responseLangInfo
  - returnURL
  - revId
  - revIds
  - rootPage
  - sectionFormat
  - sectionPreview
  - sectionTitle
  - securitySensitiveOperation
  - servedBy
  - sessionKey
  - showDeleted
  - showLinkedTo
  - showSizeDiff
  - showStrategyKeys
  - siteProp
  - sMaxAge
  - sourceLanguage
  - startHexSortKey
  - startSortKey
  - startSortKeyPrefix
  - suppressComplete
  - suppressEmpty
  - tagFilter
  - talkPage
  - targetLanguage
  - templateSandboxContentFormat
  - templateSandboxContentModel
  - templateSandboxPrefix
  - templateSandboxText
  - templateSandboxTitle
  - testActions
  - testActionsDetail
  - threadAction
  - timeCond
  - toContentFormat
  - toContentModel
  - toId
  - topOnly
  - toPst
  - toRelative
  - toRev
  - toSection
  - toSlots
  - toText
  - toTitle
  - undeleteTalk
  - unreadList
  - urlHeight
  - urlParam
  - urlWidth
  - useLang
  - userId
  - useSkin
  - watchlistExpiry
  - watchUser
  - withEditsOnly
  - wlExcludeUser
  - wlOwner
  - wlShow
  - wlToken
  - wlTypes
  - wrappedHtml
